name: dar2lator
description: A pure Dart clone of Google's calculator widget
version: 0.0.1
homepage: https://github.com/DocJava/

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter